sudo: false

language: c

addons:
  apt:
    packages:
    - texlive-latex-base

env:
- PATH=~/racket/bin:$PATH

before_install:
- racket_commit=fail
- racket_commit=$(curl http://www.cs.utah.edu/plt/snapshots/current/ | tr "\n" " " | sed -e 's/[  ][      ]*/ /g' | sed -e 's/^.*<span class="checksum"> *//' | sed -e 's| *</span>.*$||')
- if test ${#racket_commit} -ne 40 || echo $racket_commit | grep [^0-9a-f]; then racket_commit=fail; fi
- if test -e $HOME/cache/racket_commit -a "${racket_commit}" = "$(cat $HOME/cache/racket_commit)"; then echo "Using cached version of racket installer, commit ${racket_commit} == $(cat $HOME/cache/racket_commit)."; else test -e $HOME/cache && rm -fr $HOME/cache; mkdir -p $HOME/cache; echo $racket_commit > $HOME/cache/racket_commit; curl -L -o $HOME/cache/installer.sh http://www.cs.utah.edu/plt/snapshots/current/installers/racket-current-x86_64-linux-precise.sh; fi
- sh $HOME/cache/installer.sh --in-place --dest ~/racket/

cache:
  apt: true
  directories:
  - $HOME/cache

install:
- cd graph-lib
- make build-dep

script:
- make

after_script:
